dist: xenial
language: cpp
compiler: clang
before_script:
- sudo apt update
script:
- cmake .
- cmake --build .
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ualexhamster:$BINTRAY_API_KEY "https://api.bintray.com/content/alexhamster/OTUS-Cpp/homework/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
